version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: LISTENER_INSIDE://kafka:29092,LISTENER_OUTSIDE://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INSIDE://kafka:29092,LISTENER_OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INSIDE:PLAINTEXT,LISTENER_OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INSIDE
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "songids:1:1"
    depends_on:
      - zookeeper

  neo4j:
      image: neo4j:latest
      ports:
        - "7474:7474"
        - "7687:7687"
      volumes: 
        - ./neo4j/data:/data
        - ./neo4j/conf:/conf
        - ./neo4j/logs:/logs
        - ./neo4j/plugins:/plugins
        


    
