---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
spec:
  selector:
    app: kafka
  ports:
    - port: 9093
      targetPort: 9093
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-internal
spec:
  ports:
  - port: 9092
    name: plaintext
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "kafka"
  replicas: 1
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9093
        - containerPort: 9092
          name: plaintext
        env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "INTERNAL_PLAINTEXT:PLAINTEXT,EXTERNAL_PLAINTEXT:PLAINTEXT"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "INTERNAL_PLAINTEXT://kafka-internal:9092,EXTERNAL_PLAINTEXT://192.168.178.40:9093"
          - name: KAFKA_LISTENERS
            value: "INTERNAL_PLAINTEXT://0.0.0.0:9092,EXTERNAL_PLAINTEXT://0.0.0.0:9093"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "INTERNAL_PLAINTEXT"