---
apiVersion: v1
kind: Service
metadata:
  name: kafka-external
spec:
  selector:
    app: kafka
  ports:
    - port: 9093
      targetPort: 9093
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-internal
spec:
  ports:
  - port: 9092
    targetPort: 9092
  clusterIP: None
  selector:
    app: kafka