apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: neo4j
  name: neo4j
spec:
  type: LoadBalancer 
  ports:
  - name: "7474"
    port: 7474
    targetPort: 7474
  - name: "6477"
    port: 6477
    targetPort: 6477
  - name: "bolt"
    port: 7687
    targetPort: 7687
  - name: "kafka"
    port: 9092
    targetPort: 9092
  - name: "zookeeper"
    port: 2181
    targetPort: 2181

  selector:
    io.kompose.service: neo4j
status:
  loadBalancer: {}
