FROM python:3-onbuild
ADD ./artists/ /usr/src/app
ADD ./resources/ /usr/src/app

#directory structure
#usr/src/app
#   artists/
#       artists.py
#   resources/
#       spotify_auth.py
#       secrets.json

CMD [ "python","./artists/artists.py" ]